openapi: 3.0.0
servers:
  - description: Documentation for https://meowfacts.herokuapp.com, an api for facts about cats, meow facts.
    url: https://virtserver.swaggerhub.com/wh-iterabb-it/meowfacts/1.0.0
info:
  description: This is a simple API to get facts, facts about cats, meow. You can send a simple RESTful request to this enpoint and retrieve a cat fact in different languages.
  version: "1.0.1"
  title: MEOW
  contact:
    email: admin@wh.iterabb.it
  license:
    name: MIT License
    url: 'https://github.com/wh-iterabb-it/meowfacts/blob/main/LICENSE'
tags:
  - name: public
    description: Operations available to the public
paths:
  /:
    get:
      tags:
        - public
      summary: get a fact about cats, a meow fact
      operationId: queryFacts
      description: |
        By passing in the appropriate options, you can recieve a specific or more than one fact.
      parameters:
        - in: query
          name: factID
          description: pass an optional id to call a specific fact
          required: false
          schema:
            type: string
        - in: query
          name: count
          description: number of facts to return
          schema:
            type: integer
            format: int32
            minimum: 1
        - in: query
          name: lang
          description: requested locale to retrieve the cat fact in. 
          required: false
          schema:
            type: string
            enum:
              - "eng"
              - "ukr"
              - "rus"
      responses:
        '200':
          description: You just got some meowfacts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/fact'
        '400':
          description: bad input parameter
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/error'
        '404':
          description: fact not found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/error'
components:
  schemas:
    fact:
      type: object
      properties:
        data:
          type: array
          items:
            type: string
            example: "In ancient Egypt, killing a cat was a crime punishable by death."
    error: 
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 400
        message:
          type: string
          example: "Invalid language, valid languages are 'ces', 'eng', 'esp', 'ger', 'rus', 'ukr', 'ces-cz', 'eng-us', 'esp-es', 'esp-mx', 'ger-de', 'rus-ru', 'ukr-au'"
        type:
          type: string
          example: "Bad Request"
    
