{
 "title": "Weather",
 "time": { "from": "2014-01-01T00:00:00.000Z", "to": "2014-01-03T01:00:00.000Z" },
 "panels": [
  {
   "title": "London",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT temperature, log_time AS \"time\" FROM temperature WHERE city_id = 1 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Manchester",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT temperature, log_time AS \"time\" FROM temperature WHERE city_id = 2 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Liverpool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT temperature, log_time AS \"time\" FROM temperature WHERE city_id = 3 LIMIT 50 "
    }
   ]
  }
 ]
}